function report = buildAnnotatedReport(imageFile,original,usedImage,quality,result,lesions,structures,cam,cfg)

    % BUILDANNOTATEDREPORT
    % Creates PNG, TXT and PDF screening reports.
    % Reports are saved without opening external applications (safe for batches).

    %% Results directory

    resultsDir = fullfile(fileparts(mfilename('fullpath')),'results');

    if ~exist(resultsDir,'dir')
        mkdir(resultsDir);
    end

    [~,base,~] = fileparts(imageFile);

    %% ============================================================
    % CREATE ANNOTATED IMAGE
    % =============================================================

    overlay = usedImage;

    if isempty(overlay)
        overlay = original;
    end

    fig = figure('Visible','off','Color','w','Position',[100 100 1400 850]);

    tiledlayout(2,3,'Padding','compact','TileSpacing','compact');

    % Original
    nexttile;
    imshow(original);
    title('Original');

    % Image used for grading
    nexttile;
    imshow(usedImage);
    title('Image used for grading');

    % Structures
    nexttile;
    imshow(overlay);
    hold on;

    if any(~isnan(structures.opticDiscCentroid))
        plot(structures.opticDiscCentroid(1), ...
        structures.opticDiscCentroid(2), ...
        'r+','MarkerSize',14,'LineWidth',2);
    end

    if any(~isnan(structures.foveaCentroid))
        plot(structures.foveaCentroid(1), ...
        structures.foveaCentroid(2), ...
        'b+','MarkerSize',14,'LineWidth',2);
    end

    visboundaries(structures.vesselMask,'Color','w');

    title('Structures: disc/fovea/vessels');
    hold off;

    % Microaneurysm
    nexttile;

    maMask = resizeMaskForImage( ...
    lesions.microaneurysm.mask, ...
    size(original));

    lesionImage = labeloverlay( ...
    original, ...
    maMask, ...
    'Colormap',[1 0 0], ...
    'Transparency',0.65);

    imshow(lesionImage);

    title(sprintf('Microaneurysm %.3f%% | lesion evidence', ...
    lesions.microaneurysm.areaPercent));

    % Hemorrhage and exudate
    nexttile;

    heMask = resizeMaskForImage( ...
    lesions.hemorrhage.mask, ...
    size(original));

    exMask = resizeMaskForImage( ...
    lesions.exudate.mask, ...
    size(original));

    lesionImage = labeloverlay( ...
    original, ...
    heMask, ...
    'Colormap',[1 0.5 0], ...
    'Transparency',0.65);

    lesionImage = labeloverlay( ...
    lesionImage, ...
    exMask, ...
    'Colormap',[0 1 0], ...
    'Transparency',0.65);

    imshow(lesionImage);

    title('Hemorrhage + exudate | clinical lesion evidence');

    % Grad-CAM
    nexttile;

    if cam.success
        imshow(original);
        hold on;
        imagesc(cam.map,'AlphaData',0.45);
        axis image off;
        title('Grad-CAM');
        hold off;
    else
        imshow(original);
        title('Grad-CAM unavailable');
    end

    % Main title
    sgtitle(sprintf( ...
    'DR Screening | Grade %d: %s | Referable %.1f%%', ...
    result.predictedGrade, ...
    char(result.predictedClass), ...
    100 * result.referableProbability));

    % Bottom information
    annotation(fig,'textbox',[0.02 0.01 0.96 0.06], ...
    'String',sprintf( ...
    'Quality: %s (%.2f) | Confidence: %.1f%% | Review target: %ds | Structure/NV result is research-only', ...
    quality.status, ...
    quality.score, ...
    100 * result.confidence, ...
    cfg.report.reviewTargetSeconds), ...
    'EdgeColor','none', ...
    'HorizontalAlignment','center');

    %% ============================================================
    % SAVE PNG
    % =============================================================

    pngFile = fullfile(resultsDir,[base '_screening_report.png']);

    exportgraphics(fig,pngFile,'Resolution',150);

    close(fig);

    %% ============================================================
    % CREATE TXT REPORT
    % =============================================================

    reportText = fullfile(resultsDir,[base '_screening_report.txt']);

    fid = fopen(reportText,'w');

    if fid == -1
        error('Could not create text report.');
    end

    fprintf(fid,'DIABETIC RETINOPATHY SCREENING - RESEARCH PROTOTYPE\n\n');

    fprintf(fid,'Image: %s\n',imageFile);

    fprintf(fid,'Quality: %s (score %.3f)\n', ...
    quality.status,quality.score);

    fprintf(fid,'Quality message: %s\n\n',quality.message);

    fprintf(fid,'Classifier DR grade: %g (%s)\n', ...
    result.predictedGrade, char(result.predictedClass));
    if isfield(result,'finalGrade')
        fprintf(fid,'Evidence-rule screening grade: %d (%s) | agreement: %s\n', ...
        result.finalGrade.level,char(result.finalGrade.label),ternary(result.finalGrade.agreement,'yes','no'));
    end
    if isfield(result,'macularAssessment')
        fprintf(fid,'Macular screening: %s — %s\n',result.macularAssessment.status,result.macularAssessment.message);
    end

    fprintf(fid,'Classifier confidence: %.2f%%\n', ...
    100 * result.confidence);

    fprintf(fid,'Referable probability (grades 2-4): %.2f%%\n', ...
    100 * result.referableProbability);

    fprintf(fid,'Referable decision: %s\n\n', ...
    ternary(result.referable,'REFER','NON-REFER'));

    fprintf(fid,'Class probabilities: ');

    fprintf(fid,'%.4f ',result.probabilities);

    fprintf(fid,'\n\n');

    fprintf(fid,'Lesion evidence:\n');

    fprintf(fid,'  Microaneurysm: %s, area %.4f%%, components %d\n', ...
    ternary(lesions.microaneurysm.present,'present','not detected'), ...
    lesions.microaneurysm.areaPercent, ...
    size(lesions.microaneurysm.subpixelCentroids,1));

    fprintf(fid,'  Hemorrhage: %s, area %.4f%%, components %d\n', ...
    ternary(lesions.hemorrhage.present,'present','not detected'), ...
    lesions.hemorrhage.areaPercent, ...
    size(lesions.hemorrhage.subpixelCentroids,1));

    fprintf(fid,'  Exudate: %s, area %.4f%%, components %d\n', ...
    ternary(lesions.exudate.present,'present','not detected'), ...
    lesions.exudate.areaPercent, ...
    size(lesions.exudate.subpixelCentroids,1));

    fprintf(fid,'\n');

    fprintf(fid,'Optic disc centroid: [%.1f, %.1f]\n', ...
    structures.opticDiscCentroid(1), ...
    structures.opticDiscCentroid(2));

    fprintf(fid,'Fovea centroid: [%.1f, %.1f]\n', ...
    structures.foveaCentroid(1), ...
    structures.foveaCentroid(2));

    fprintf(fid,'Vessel density: %.4f\n', ...
    structures.vesselDensity);

    fprintf(fid,'NV heuristic: %s\n', ...
    ternary(structures.neovascularizationSuspicious, ...
    'suspicious','not suspicious'));

    fprintf(fid,'\n');

    fprintf(fid,['Clinical safety note: This is a decision-support prototype. ' ...
    'A referral decision must be confirmed by a qualified eye-care ' ...
    'professional, especially for ungradable or discordant cases.\n']);

    fclose(fid);


%% ============================================================
% CREATE PDF
% =============================================================

pdfFile = fullfile(resultsDir,[base '_screening_report.pdf']);

% Letter page, portrait.
pdfFig = figure( ...
    'Visible','off', ...
    'Color','white', ...
    'Units','inches', ...
    'Position',[0 0 8.5 11], ...
    'PaperUnits','inches', ...
    'PaperSize',[8.5 11], ...
    'PaperPosition',[0 0 8.5 11], ...
    'InvertHardcopy','off');

%% ------------------------------------------------------------
% PAGE HEADER
% ------------------------------------------------------------

annotation(pdfFig,'textbox',[0.05 0.945 0.90 0.035], ...
    'String','DIABETIC RETINOPATHY SCREENING REPORT', ...
    'EdgeColor','none', ...
    'Color',[0 0 0], ...
    'HorizontalAlignment','center', ...
    'FontSize',18, ...
    'FontWeight','bold');

annotation(pdfFig,'textbox',[0.05 0.912 0.90 0.025], ...
    'String','Research Prototype  •  Clinician Review Required', ...
    'EdgeColor','none', ...
    'Color',[0.25 0.25 0.25], ...
    'HorizontalAlignment','center', ...
    'FontSize',10);

%% ------------------------------------------------------------
% LARGE ANNOTATED IMAGE
% ------------------------------------------------------------

% Use most of the upper half of the page.
imgAx = axes( ...
    'Parent',pdfFig, ...
    'Units','normalized', ...
    'Position',[0.055 0.475 0.89 0.415], ...
    'Color','white');

imshow(pngFile,'Parent',imgAx);
axis(imgAx,'off');

%% ------------------------------------------------------------
% SCREENING SUMMARY
% ------------------------------------------------------------

summaryText = sprintf([ ...
    'SCREENING SUMMARY\n'  ...
    'Quality: %s (%.3f)\n' ...
    'Quality message: %s\n' ...
    'DR Grade: %d (%s)\n' ...
    'Classifier confidence: %.2f%%\n' ...
    'Referable probability: %.2f%%\n' ...
    'Referable decision: %s\n'], ...
    quality.status, ...
    quality.score, ...
    quality.message, ...
    result.predictedGrade, ...
    char(result.predictedClass), ...
    100 * result.confidence, ...
    100 * result.referableProbability, ...
    ternary(result.referable,'REFER','NON-REFER'));

%% ------------------------------------------------------------
% LESION EVIDENCE
% ------------------------------------------------------------

lesionText = sprintf([ ...
    'LESION EVIDENCE\n' ...
    'Microaneurysm: %s  |  Area %.4f%%  |  Components %d\n' ...
    'Hemorrhage: %s  |  Area %.4f%%  |  Components %d\n' ...
    'Exudate: %s  |  Area %.4f%%  |  Components %d\n'], ...
    ternary(lesions.microaneurysm.present,'Present','Not detected'), ...
    lesions.microaneurysm.areaPercent, ...
    size(lesions.microaneurysm.subpixelCentroids,1), ...
    ternary(lesions.hemorrhage.present,'Present','Not detected'), ...
    lesions.hemorrhage.areaPercent, ...
    size(lesions.hemorrhage.subpixelCentroids,1), ...
    ternary(lesions.exudate.present,'Present','Not detected'), ...
    lesions.exudate.areaPercent, ...
    size(lesions.exudate.subpixelCentroids,1));

%% ------------------------------------------------------------
% STRUCTURE ANALYSIS
% ------------------------------------------------------------

structureText = sprintf([ ...
    'STRUCTURE ANALYSIS\n' ...
    'Optic disc centroid: [%.1f, %.1f]\n' ...
    'Fovea centroid: [%.1f, %.1f]\n' ...
    'Vessel density: %.4f\n' ...
    'NV heuristic: %s\n'], ...
    structures.opticDiscCentroid(1), ...
    structures.opticDiscCentroid(2), ...
    structures.foveaCentroid(1), ...
    structures.foveaCentroid(2), ...
    structures.vesselDensity, ...
    ternary(structures.neovascularizationSuspicious, ...
        'Suspicious','Not suspicious'));

%% ------------------------------------------------------------
% TWO-COLUMN INFORMATION AREA
% ------------------------------------------------------------

annotation(pdfFig,'textbox',[0.055 0.245 0.425 0.205], ...
    'String',summaryText, ...
    'EdgeColor',[0.75 0.75 0.75], ...
    'LineWidth',0.8, ...
    'Color',[0 0 0], ...
    'FontSize',9.5, ...
    'VerticalAlignment','top', ...
    'Interpreter','none', ...
    'Margin',10);

annotation(pdfFig,'textbox',[0.52 0.245 0.425 0.205], ...
    'String',[lesionText newline structureText], ...
    'EdgeColor',[0.75 0.75 0.75], ...
    'LineWidth',0.8, ...
    'Color',[0 0 0], ...
    'FontSize',9.5, ...
    'VerticalAlignment','top', ...
    'Interpreter','none', ...
    'Margin',10);

%% ------------------------------------------------------------
% CLINICAL SAFETY NOTE
% ------------------------------------------------------------

safetyText = sprintf([ ...
    'CLINICAL SAFETY NOTE\n' ...
    'This is a decision-support prototype. A referral decision must be ' ...
    'confirmed by a qualified eye-care professional, especially for ' ...
    'ungradable or discordant cases.']);

annotation(pdfFig,'textbox',[0.055 0.115 0.89 0.085], ...
    'String',safetyText, ...
    'EdgeColor',[0.55 0.55 0.55], ...
    'LineWidth',0.8, ...
    'Color',[0 0 0], ...
    'FontSize',9, ...
    'VerticalAlignment','middle', ...
    'HorizontalAlignment','left', ...
    'Interpreter','none', ...
    'Margin',10);

%% ------------------------------------------------------------
% FOOTER
% ------------------------------------------------------------

footerText = sprintf( ...
    'Review target: %ds  •  Structure/NV result is research-only', ...
    cfg.report.reviewTargetSeconds);

annotation(pdfFig,'textbox',[0.055 0.055 0.89 0.035], ...
    'String',footerText, ...
    'EdgeColor','none', ...
    'Color',[0.35 0.35 0.35], ...
    'HorizontalAlignment','center', ...
    'FontSize',8.5);

%% ------------------------------------------------------------
% EXPORT PDF
% ------------------------------------------------------------

% Export the actual full-page figure rather than a small raster-style
% content region.
exportgraphics(pdfFig,pdfFile, ...
    'ContentType','vector', ...
    'BackgroundColor','white');

close(pdfFig);



    %% ============================================================
    % RETURN REPORT
    % =============================================================

    report = struct( ...
    'pngFile',pngFile, ...
    'textFile',reportText, ...
    'pdfFile',pdfFile, ...
    'baseName',base);

    %% ============================================================
    % OPEN PDF AUTOMATICALLY
    % =============================================================

    if isfile(pdfFile), fprintf('\nPDF report created:\n%s\n',pdfFile); end

end


%% ============================================================
% HELPER: TERNARY
% ============================================================

function out = ternary(condition,valueTrue,valueFalse)

    if condition
        out = valueTrue;
    else
        out = valueFalse;
    end

end


%% ============================================================
% HELPER: RESIZE MASK
% ============================================================

function maskOut = resizeMaskForImage(maskIn,imageSize)

    if isempty(maskIn)

        maskOut = false(imageSize(1),imageSize(2));

        return;

    end

    maskIn = logical(maskIn);

    if isequal(size(maskIn),imageSize(1:2))

        maskOut = maskIn;

    else

        maskOut = imresize(maskIn,imageSize(1:2),'nearest');

    end

end
